# 日志配置
logging:
  level:
    root: INFO
    cn.ts: DEBUG  # 项目包下的日志级别设为 DEBUG
    org.springframework.ai: DEBUG

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 15 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 25 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1

  ai:
    openai:
      api-key: sk-1c7794d42765440fa4913b1cbb097fb2 #ms-89889fc4-c573-4a04-85ac-e5ac323c2374
      base-url: https://dashscope.aliyuncs.com/compatible-mode #https://api-inference.modelscope.cn/
      chat:
        options:
          model: qwen-flash #Qwen/Qwen3-235B-A22B-Instruct-2507
  # Redis配置
#redis:
#  sdk:
#    config:
#      host: 127.0.0.1
#      port: 16379
#      pool-size: 10
#      min-idle-size: 5
#      idle-timeout: 30000
#      connect-timeout: 5000
#      retry-attempts: 3
#      retry-interval: 1000
#      ping-interval: 60000
#      keep-alive: true

jwt:
  secret: ShopSecretKey2025ForJWTTokenGenerationAndValidation
  expiration: 2000000000    # 24小时，单位毫秒
  header: Authorization
  prefix: "Bearer "

# MyBatis配置
#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
#  type-aliases-package: cn.ts.shop.module
#  configuration:
#    map-underscore-to-camel-case: true

